mysite/lib/urls.py
from django.urls import path
from . import views

app_name = 'lib'
urlpatterns = [
    path('detail/', views.detail, name='detail'),
    path('addBook/', views.addBook, name='addBook'),
    #path('delBook/<int:book_no>', views.deleteBook, name='delBook'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('lib/', include('lib.urls')),
    path('admin/', admin.site.urls),
]

mysite/lib/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    no = models.IntegerField(primary_key=True, verbose_name='书籍编号')
    name = models.CharField(max_length=64, verbose_name='书籍')
    author = models.CharField(max_length=64, verbose_name='作者')
    pub_house = models.CharField(max_length=100, verbose_name='出版社')
    pub_date = models.DateField(null=True, verbose_name='出版日期')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tb_book'
        verbose_name = '图书'
        verbose_name_plural = '图书'

mysite/lib/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from lib.models import Book
# Create your views here.


def detail(request):
    book_list = Book.objects.order_by('no')[:10]
    context = {'book_list': book_list}
    return render(request, 'detail.html', context)


def addBook(request):
    if request.method == 'POST':
        temp_no = request.POST['no']
        temp_name = request.POST['name']
        temp_author = request.POST['author']
        temp_pub_house = request.POST['pub_house']

    from django.utils import timezone
    temp_book = Book(no=temp_no, name=temp_name, author=temp_author,
                     pub_house=temp_pub_house, pub_date=timezone.now())
    temp_book.save()

    # 重定向
    return HttpResponseRedirect(reverse('lib:detail'))


def deleteBook(request, book_no):
    bookID = book_no
    Book.objects.filter(no=bookID).delete()
    return HttpResponseRedirect(reverse('lib:detail'))

mysite/lib/templates/detail.html
<!DOCTYPE html>
<html>
<head>
<meta charset = "utf-8">
<title>huluobai</title>

<head>

<body>

    <h1>Book List</h1>
<table>
    <tr>

        <th>书籍编号</th>
        <th>书名</th>
        <th>作者</th>
        <th>出版社</th>
        <th>出版时间</th>
    </tr>
{% for book in book_list.all %}
    <tr>
        <td>{{ book.no }}</td>
        <td>{{ book.name }}</td>
        <td>{{ book.author }}</td>
        <td>{{ book.pub_house }}</td>
        <td>{{ book.pub_date }}</td>


    </tr>
{% endfor %}
</table>
</body>

<form action="{% url 'lib:addBook' %}" method="post" name="addBook">
    {% csrf_token %}
    <p><span>编号：</span><input type="text"  name="name"></p>
    <p><span>书名：</span><input type="text"  name="name"></p>
    <p><span>作者：</span><input type="text"  name="author"></p>
    <p><span>出版社：</span><input type="text"  name="pub_house"></p>
    <p><span>出版时间：</span><input type="text"  name="pub_house"></p>
    <input type="submit" value="添加">
</form>

<html>